### ISSUE TITLE
Error: Python module tensorflow.python.keras was not found.

### ISSUE THREAD

**Issue by eiichi2009** [rstudio/keras#987]
I installed keras and tensorflow in my python 3.7.4 environment and I can import them
But  load_model_hdf5() is not working but reporting the following error:
Error: Python module tensorflow.python.keras was not found.

> library(tensorflow)
> library(keras)
> m <- load_model_hdf5("dnn.h5")
2020-02-18 10:00:27.107843: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /nzsc4
2020-02-18 10:00:27.107992: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRA4
2020-02-18 10:00:27.108010: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed proper.
Error: Installation of TensorFlow not found.
Python environments searched for 'tensorflow' package:
 /scratch/python/3.7.4/bin/python3.7
 /usr/bin/python
You can install TensorFlow using the install_tensorflow() function.
> m <- load_model_hdf5("dnn.h5")
Error: Python module tensorflow.python.keras was not found.
Detected Python configuration:
python:         /scratch/python/3.7.4/bin/python
libpython:      /scratch/python/3.7.4/lib/libpython3.7m.so
pythonhome:     /scratch/python/3.7.4:/scratch/python/3.7.4
version:        3.7.4 (default, Aug 13 2019, 20:35:49)  [GCC 7.3.0]
numpy:          /scratch/python/3.7.4/lib/python3.7/site-packages/numpy
numpy_version:  1.17.2
tensorflow:     /scratch/python/3.7.4/lib/python3.7/site-packages/tensorflow
python versions found: 
 /scratch/python/3.7.4/bin/python
 /usr/bin/python
> 

When I ran py_discover_config(), it looks like those packages are there 

> py_discover_config("keras")
python:         /scratch/python/3.7.4/bin/python
libpython:      /scratch/python/3.7.4/lib/libpython3.7m.so
pythonhome:     /scratch/python/3.7.4:/scratch/python/3.7.4
version:        3.7.4 (default, Aug 13 2019, 20:35:49)  [GCC 7.3.0]
numpy:          /scratch/python/3.7.4/lib/python3.7/site-packages/numpy
numpy_version:  1.17.2
keras:          /scratch/python/3.7.4/lib/python3.7/site-packages/keras
python versions found: 
 /scratch/python/3.7.4/bin/python
 /usr/bin/python

> py_discover_config("h5py")
python:         /scratch/python/3.7.4/bin/python
libpython:      /scratch/python/3.7.4/lib/libpython3.7m.so
pythonhome:     /scratch/python/3.7.4:/scratch/python/3.7.4
version:        3.7.4 (default, Aug 13 2019, 20:35:49)  [GCC 7.3.0]
numpy:          /scratch/python/3.7.4/lib/python3.7/site-packages/numpy
numpy_version:  1.17.2
h5py:           /scratch/python/3.7.4/lib/python3.7/site-packages/h5py
python versions found: 
 /scratch/python/3.7.4/bin/python
 /usr/bin/python
> py_discover_config("tensorflow")
python:         /scratch/python/3.7.4/bin/python
libpython:      /scratch/python/3.7.4/lib/libpython3.7m.so
pythonhome:     /scratch/python/3.7.4:/scratch/python/3.7.4
version:        3.7.4 (default, Aug 13 2019, 20:35:49)  [GCC 7.3.0]
numpy:          /scratch/python/3.7.4/lib/python3.7/site-packages/numpy
numpy_version:  1.17.2
tensorflow:     /scratch/python/3.7.4/lib/python3.7/site-packages/tensorflow
python versions found: 
 /scratch/python/3.7.4/bin/python
 /usr/bin/python
> 

I ran install_tensorflow() but it did not help. My R version is 

[root@host1 ~]# R --version
R version 3.5.3 (2019-03-11) -- "Great Truth"

My machine is Redhat 6.10 x86_64

eii

**Comment by skeydan** [comment]
Does the following Python program work for you?

```
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)
```

?

**Comment by eiichi2009** [comment]
Hi Skeydan Thank you!  No it failed at mnist.load_data(). My machine does not have access to the data download site.. But it looks like the first and the second lines worked without issue. 

[root@host1 tmp]# /scratch/python/3.7.4/bin/python /tmp/test.py
2020-02-19 09:53:55.718417: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr4
2020-02-19 09:53:55.718599: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRA4
2020-02-19 09:53:55.718617: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed proper.
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
Traceback (most recent call last):
  File "/scratch/python/3.7.4/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/scratch/python/3.7.4/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/scratch/python/3.7.4/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/scratch/python/3.7.4/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/scratch/python/3.7.4/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/scratch/python/3.7.4/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/scratch/python/3.7.4/lib/python3.7/http/client.py", line 1414, in connect
    server_hostname=server_hostname)
  File "/scratch/python/3.7.4/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/scratch/python/3.7.4/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/scratch/python/3.7.4/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/python/3.7.4/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/data_utils.py", line 264, in get_file
    urlretrieve(origin, fpath, dl_progress)
  File "/scratch/python/3.7.4/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/scratch/python/3.7.4/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/scratch/python/3.7.4/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/scratch/python/3.7.4/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/scratch/python/3.7.4/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/scratch/python/3.7.4/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/scratch/python/3.7.4/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>

**Comment by skeydan** [comment]
Hm, thanks, I see - could you then just try loading that model in Python and see if that works?

**Comment by eiichi2009** [comment]
It seems to be working fine. I downloaded mnist.npz separately, modified load_data() function, then ran it.
(x_train, y_train),(x_test, y_test) = mnist.load_data("/tmp/mnist.npz")


[root@host1 ~]# /scratch/python/3.7.4/bin/python /tmp/test.py

2020-02-20 09:45:46.457823: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr4

2020-02-20 09:45:46.458143: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRA4

2020-02-20 09:45:46.458188: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed proper.

2020-02-20 09:45:55.450884: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local4

2020-02-20 09:45:55.450937: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)

2020-02-20 09:45:55.450971: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (netezza15pri): /proc/driver/nvidia/version does not exist

2020-02-20 09:45:55.526752: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2399925000 Hz

2020-02-20 09:45:55.531509: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55dc81c76a00 initialized for platform Host (this does not guarantee that XLA will be used). Devices:

2020-02-20 09:45:55.531542: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version

Train on 60000 samples

Epoch 1/5

60000/60000 [==============================] - 6s 105us/sample - loss: 0.2988 - accuracy: 0.9135

Epoch 2/5

60000/60000 [==============================] - 7s 113us/sample - loss: 0.1431 - accuracy: 0.9572

Epoch 3/5

60000/60000 [==============================] - 7s 118us/sample - loss: 0.1062 - accuracy: 0.9683

Epoch 4/5

60000/60000 [==============================] - 7s 120us/sample - loss: 0.0864 - accuracy: 0.9735

Epoch 5/5

60000/60000 [==============================] - 7s 119us/sample - loss: 0.0743 - accuracy: 0.9766

10000/10000 [==============================] - 1s 117us/sample - loss: 0.0803 - accuracy: 0.9752

**Comment by skeydan** [comment]
That's good to know! Does the equivalent work for you in R as well, or put differently, is the problem in R only with `load_model_hdf5` or other commands as well?

**Comment by eiichi2009** [comment]
Thank you Skeydan again!  I haven't run much test yet but load_model_hdf5() is the first one to show the error.

**Comment by eiichi2009** [comment]
Hi
I tried running my R code with --verbose flag.

> library(tensorflow)
now dyn.load("/opt2/lib64/R/library/Rcpp/libs/Rcpp.so") ...
Garbage collection 2 = 1+0+1 (level 0) ... 
18.5 Mbytes of cons cells used (55%)
5.4 Mbytes of vectors used (8%)
now dyn.load("/opt2/lib64/R/library/jsonlite/libs/jsonlite.so") ...
Garbage collection 3 = 2+0+1 (level 0) ... 
20.0 Mbytes of cons cells used (59%)
5.7 Mbytes of vectors used (9%)
now dyn.load("/opt2/lib64/R/library/reticulate/libs/reticulate.so") ...
now dyn.load("/opt2/lib64/R/library/base64enc/libs/base64enc.so") ...
> library(keras)
Garbage collection 4 = 3+0+1 (level 0) ... 
21.3 Mbytes of cons cells used (63%)
5.9 Mbytes of vectors used (9%)
> keras::load_model_hdf5("/tmp/h.h5")
now dyn.load("/opt2/lib64/R/library/rappdirs/libs/rappdirs.so") ...
Garbage collection 5 = 4+0+1 (level 0) ... 
23.9 Mbytes of cons cells used (71%)
6.6 Mbytes of vectors used (10%)
Error: Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 /scratch/python/3.7.4/bin/python3.7
 /scratch/python/3.7.4/bin/python3.7
 /usr/bin/python

You can install TensorFlow using the install_tensorflow() function.
 >R_ReplConsole(): before "for(;;)" {main.c}
> 

then I ran "install_tensorflow()", which completed successfully. But then I ran keras::load_model_h5py() again and got the same error.

> keras::load_model_hdf5("/tmp/h.h5")
Error: Python module tensorflow.keras was not found.

Detected Python configuration:

python:         /root/.virtualenvs/r-reticulate/bin/python
libpython:      /scratch/python/3.7.4/lib/libpython3.7m.so
pythonhome:     /scratch/python/3.7.4:/scratch/python/3.7.4
version:        3.7.4 (default, Aug 13 2019, 20:35:49)  [GCC 7.3.0]
numpy:          /scratch/python/3.7.4/lib/python3.7/site-packages/numpy
numpy_version:  1.17.2
tensorflow:     /root/.virtualenvs/r-reticulate/lib/python3.7/site-packages/tensorflow

python versions found: 
 /root/.virtualenvs/r-reticulate/bin/python
 /scratch/python/3.7.4/bin/python3
 /usr/bin/python

 >R_ReplConsole(): before "for(;;)" {main.c}
> 

Why keras::load_model_h5py() cannot find tensorflow.keras? Is it something I need to install additionally?

**Comment by dfalbel** [comment]
This should be fixed in the dev version of keras. Please install from github with `remotes::install_github("rstudio/keras")`.

**Comment by t-kalinowski** [comment]
Hello,

The code that installs tensorflow and keras has been [refactored](https://github.com/rstudio/keras/pull/1251).
Please update to the latest versions of reticulate, tensorflow, and keras:
```R
install.packages("remotes")
remotes::install_github(paste0("rstudio/", c("reticulate", "tensorflow", "keras")))
reticulate::install_miniconda() # skip this if you want to self-install conda or use venv
keras::install_keras()
```

Please let us know if after updating you are still encountering installation issues:
https://github.com/rstudio/tensorflow/issues/new
